"""
Django settings for safehome project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# --- 기본 경로/환경 ---
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --- 외부 키/환경 변수 ---
VWORLD_API_KEY = os.getenv("V_WORLD_KEY")
SEOUL_DATA_KEY = os.getenv("SEOUL_DATA_KEY")
BUSINESS_JUSO_KEY = os.getenv("BUSINESS_JUSO_KEY")
AIR_QUALITY_KEY = os.getenv("AIR_QUALITY_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
API_URL = os.getenv("API_URL")
A_PICK_KEY = os.getenv("A_PICK_KEY")

# 침수정보 API 키
DATA_GO_KR_ENCODING_KEY = os.getenv("DATA_GO_KR_ENCODING_KEY")
DATA_GO_KR_DECODING_KEY = os.getenv("DATA_GO_KR_DECODING_KEY")

# --- 보안/디버그 ---
SECRET_KEY = 'django-insecure-*r1-ojihfw4vb39-e=e4)v--wr+-^bs!n1d81!k033vjd39how'
DEBUG = True
ALLOWED_HOSTS = ["*"]  # 개발 중 외부 접속 허용:contentReference[oaicite:1]{index=1}

# --- 앱 등록 ---
INSTALLED_APPS = [
    # Django 기본
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd-party
    'rest_framework',            # DRF:contentReference[oaicite:2]{index=2}
    'drf_spectacular',           # drf-spectacular (문서화)

    # Local apps
    'apps.users',
    'apps.address',
    'apps.gpt',
    'apps.report',
    'apps.contract',
    'apps.image',
    'apps.testing',              # flood 프록시 뷰가 있는 앱
]

INSTALLED_APPS += ["drf_spectacular", "drf_spectacular_sidecar"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safehome.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safehome.wsgi.application'

# --- 데이터베이스 ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}

# --- 비밀번호 검증 ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- 국제화/시간대 ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- 정적/미디어 ---
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'    # 업로드 파일 저장:contentReference[oaicite:3]{index=3}

TEXT_ROOT = BASE_DIR / "textfiles"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',  # 파일 업로드 지원:contentReference[oaicite:4]{index=4}
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',     # 개발 단계 기본 허용:contentReference[oaicite:5]{index=5}
    ],
    'DEFAULT_PAGINATION_CLASS': "rest_framework.pagination.PageNumberPagination",
    'PAGE_SIZE': 20,
}

ALLOWED_HOSTS = ['*']

SPECTACULAR_SETTINGS = {
    "TITLE": "SafeHome API",
    "DESCRIPTION": "API docs",
    "VERSION": "1.0.0",
    # 필요시:
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "local8000"},
        {"url": "http://localhost:80", "description": "local80"},
        {"url": "http://ec2-13-124-113-86.ap-northeast-2.compute.amazonaws.com:8000", "description": "server8000"},
        {"url": "http://ec2-13-124-113-86.ap-northeast-2.compute.amazonaws.com:80", "description": "server80"},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
}
