# Generated by Django 5.2.5 on 2025-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
