# Generated by Django 5.2.1 on 2025-08-21 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_tempprice_report_run_address_buildinginfo_and_more'),
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportRun',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20),
        ),
    ]
