# Generated by Django 5.2.5 on 2025-08-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_reportdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='description',
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='score',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
