version: "3.9"

services:
  safehome:
    container_name: safehome
    image: poatansanyo/safehome:1.0.0
    build:
      context: ./project
    ports:
      - "8000:8000"
    volumes:
      - ./project/media:/app/media
      - ./project/staticfiles:/app/staticfiles
      - ./project/db:/app/db
    command: >
      sh -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn safehome.wsgi:application --bind 0.0.0.0:8000
          "
  nginx:
    container_name: safehome_nginx
    image: poatansanyo/safehome_nginx:1.0.0
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./project/media:/media
      - ./project/staticfiles:/static
    



