# Generated by Django 5.2.5 on 2025-08-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DangerCheckList',
        ),
    ]
