# Generated by Django 5.2.5 on 2025-08-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_addr', models.CharField(max_length=255)),
                ('bd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('adm_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('sgg_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('mt_yn', models.CharField(default='0', max_length=1)),
                ('lnbr_mnnm', models.CharField(blank=True, max_length=20, null=True)),
                ('lnbr_slno', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_addresses', to='report.reportrun')),
            ],
        ),
    ]
