# Generated by Django 5.2.5 on 2025-08-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempaddress',
            old_name='road_addr',
            new_name='road_address',
        ),
    ]
