# Generated by Django 5.2.5 on 2025-08-21 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_rename_road_addr_tempaddress_road_address'),
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_prices', to='report.reportrun')),
            ],
        ),
    ]
