# Generated by Django 5.2.5 on 2025-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_aircondition_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircondition',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='buildinginfo',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
