# Generated by Django 5.2.5 on 2025-08-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_tempaddress_report_run'),
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempaddress',
            name='report_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_address', to='report.reportrun'),
        ),
        migrations.AlterField(
            model_name='tempprice',
            name='report_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_prices', to='report.reportrun'),
        ),
    ]
