# Generated by Django 5.2.1 on 2025-08-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_tempaddress_report_run_and_more'),
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempprice',
            name='report_run',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_address', models.CharField(max_length=255)),
                ('bd_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('adm_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('sgg_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('mt_yn', models.CharField(default='0', max_length=1)),
                ('lnbr_mnnm', models.CharField(blank=True, max_length=20, null=True)),
                ('lnbr_slno', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='report.report')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_info', to='report.report')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_year_rent', models.BooleanField()),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_price', to='report.report')),
            ],
        ),
        migrations.DeleteModel(
            name='TempAddress',
        ),
        migrations.DeleteModel(
            name='TempPrice',
        ),
    ]
