# Generated by Django 5.2.5 on 2025-08-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_avgprice'),
        ('report', '0003_delete_reportrun_report_created_at_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_registry', to='report.report')),
            ],
        ),
    ]
