# Generated by Django 5.2.5 on 2025-08-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContractData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(blank=True, default=dict)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_data', to='contract.contract')),
            ],
        ),
    ]
