# Generated by Django 5.2.5 on 2025-08-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_tempprice'),
        ('report', '0002_delete_dangerchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempaddress',
            name='report_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_address', to='report.reportrun'),
        ),
    ]
