# Generated by Django 5.2.1 on 2025-08-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_tempprice_report_run_address_buildinginfo_and_more'),
        ('report', '0003_delete_reportrun_report_created_at_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_year_price', models.FloatField(default=0.0)),
                ('avg_month_security_price', models.FloatField(default=0.0)),
                ('avg_month_rent', models.FloatField(default=0.0)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avg_price', to='report.report')),
            ],
        ),
    ]
