# Generated by Django 5.2.5 on 2025-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertendency',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
